Use enum for dependency compliance
open-cluster-management-io/governance-policy-addon-controller pull request #49
Opened 2023-01-04 18:37 UTC by willkutler

Adds an enum for `dependencies[].compliance` and `extraDependencies[].compliance` to block creation of policies with that field set incorrectly. This will fix policies creating with invalid dependencies.

refs:
- https://issues.redhat.com/browse/ACM-2148

2023-01-04 18:56 UTC, mprahl commented
/hold

@willkutler did you also set the kubebuilder markers in the config-policy-controller?

2023-01-04 19:00 UTC, mprahl commented
@willkutler, I also noticed the enum is different here:
https://github.com/stolostron/console/pull/2317/files#diff-650ab4818c53a4c05b1eb15787248343803c6ded138db36edf237b6bd5c90b16R30

This should likely be updated with this change as well.

2023-01-04 19:21 UTC, dhaiducek requested changes
I agree with @mprahl that the propagator probably needs an update in tandem with this PR.

It looks like https://github.com/open-cluster-management-io/governance-policy-propagator/pull/59 updated the `ComplianceState`, but the Dependency structs use a string type for its `Compliance` field instead of the `ComplianceState` struct:
- https://github.com/open-cluster-management-io/governance-policy-propagator/blob/5f6402dedafafa32cd20fc6f97d7d72758bd80d6/api/v1/policy_types.go#L62-L63

2023-01-04 21:08 UTC, mprahl commented
@willkutler could you please squash your commits?

2023-01-05 14:24 UTC, willkutler commented
@mprahl is this good to go?

2023-01-05 14:36 UTC, mprahl approved these changes

2023-01-05 15:07 UTC, willkutler commented
/unhold

2023-01-07 11:55 UTC, dhaiducek approved these changes

2023-01-07 11:55 UTC, merged